version: "3.0"
services:
  mongodb:
    # 容器的名称为 mymongo
    container_name: my-mg
    # 使用的镜像名称
    image: mongo:latest
    # 当 docker 服务启动后，自动启动 mongodb 容器
    restart: always
    # 对外映射的端口
    ports:
      - "27017:27017"
    environment:
      # 初始化一个 root 角色的用户 root 密码是 root
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    # 宿主机硬盘目录映射容器内的存放数据的目录
    volumes:
      - /root/data/docker/mg/data:/data/db
    networks:
      - net1
    # 增加启动参数，--auth，表示连接 mongodb 需要用户名和密码
    command:
      - "--auth"

  spiderpy:
    container_name: jishispider
    image: registry.cn-hangzhou.aliyuncs.com/rikiguan/spidermg:1.0.2
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - net1
    depends_on:
      - mongodb
    volumes:
      - /root/data/docker/jishi/data:/opt/jishi/data
      - /root/data/docker/jishi/log:/opt/jishi/log

networks:
  net1:
    external: true